---
config:
  themeVariables:
    fontSize: 18px
  flowchart:
    nodeSpacing: 28
    rankSpacing: 34
---
flowchart TD
  A[Kauf einer Sache] --> B[Kaufsache unverzüglich prüfen<br/><em>Art. 201 Abs. 1 OR</em>]

  B --> C{Offensichtlicher<br/>Sachmangel?}
  B -- Falls versäumt --> G[Genehmigung der Sache<br/><em>Art. 201 Abs. 2 OR</em>]

  C -- Ja --> D[Mangel unverzüglich rügen<br/><em>Art. 201 Abs. 1 und 3 OR</em>]
  C -- Nein --> E{Später auftauchender<br/>verdeckter Sachmangel?}

  E -- Nein --> OK((☺))
  E -- Ja --> F{Entdeckung innerhalb von<br/>zwei Jahren ab Ablieferung?}

  F -- Ja --> D
  F -- Nein --> H[Rechte verjähren<br/><em>Art. 210 Abs. 1 OR</em>]

  D -- Falls versäumt --> G
  D --> I[Wahlrecht ausüben]

  I --> J[Wandelung wählen<br/><em>Art. 205 Abs. 1 OR</em>]
  I --> L[Minderung wählen<br/><em>Art. 205 f. OR</em>]
  I --> N[Ersatzlieferung² wählen<br/><em>Art. 206 Abs. 1 OR</em>]

  J --> K[+<br/>Schadenersatz fordern<br/><em>Art. 208 Abs. 2 und 3 OR</em>]
  L --> M[+<br/>Schadenersatz fordern<br/><em>Art. 97 OR</em>]
  N --> O[+<br/>Schadenersatz fordern<br/><em>Art. 97 OR</em>]

  G ~~~ D
  H ~~~ N


  classDef box fill:#fff,stroke:#777,stroke-width:1px,color:#111;
  classDef decision fill:#fff,stroke:#777,stroke-width:1px,color:#111;
  classDef finalNode fill:#fff,stroke:#777,stroke-width:1px,color:#111;
  classDef footnote fill:transparent,stroke:transparent,color:#111;

  class A,B,D,G,H,I,J,K,L,M,N,O box;
  class C,E,F decision;
  class OK finalNode;

